name: Build & Deploy

on:
  push:
    paths:
      - "src"
      - "package.json"
      - ".github/workflows"
    branches:
      - main
  pull_request:
    paths:
      - "src"
      - "package.json"
      - ".github/workflows"
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install NPM packages
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload to pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build
          name: github-pages
          retention-days: 7

            # report:
            # name: Report
            # runs-on: ubuntu-latest
            # needs: build
            #
            # steps:
            # - name: Report build status
            # run: 'gh api -X POST "repos/$GITHUB_REPOSITORY/pages/telemetry" \
            # -F github_run_id="$GITHUB_RUN_ID" \
          # -F conclusion="$CONCLUSION"'

  deploy:
    name: Deploy
    needs: build
    environment:
      name: github-pages
      url: https://ossian.dev
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          timeout: 600000
          error_count: 10
          reporting_interval: 5000
          artifact_name: github-pages
          preview: false
